[package]
name = "day9"
version = "0.1.0"
authors = ["Siegfried Puchbauer <siegfried.puchbauer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#[macro_use]
lazy_static = "1"
regex = "1"
itertools = "*"