name: Update Index
on:
    push:
        branches:
            - main
env:
    CARGO_TERM_COLOR: always
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      tools/aoc-cli/target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('tools/aoc-cli/Cargo.lock') }}
            - run: cargo install --path tools/aoc-cli
            - run: aoc generate-index
            - name: push changes
              run: |
                  git config --global user.name 'Siegfried Puchbauer'
                  git config --global user.email 'ziegfried@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
                  git checkout main
                  git commit -am "update index" || echo "no changes?"
                  git push origin main
